---
- name: Installing supervisord
  apt: name=supervisor state=present
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Restarting supervisord
  service: name=supervisor state=restarted
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Adding Apache Storm Supervisor to supervisord
  template: src=storm-supervisor.conf.j2 dest=/etc/supervisor/conf.d/storm-supervisor.conf
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Adding Apache Storm Logviewer to supervisord
  template: src=storm-logviewer.conf.j2 dest=/etc/supervisor/conf.d/storm-logviewer.conf
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Starting Apache Storm Supervisor
  supervisorctl: name=storm-supervisor state=restarted
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Starting Apache Storm Logviewer
  supervisorctl: name=storm-logviewer state=restarted
  remote_user: "{{ user }}"
  become: yes
  become_user: root
